sudo: false
language: python
python:
  - "2.7"

install: "python setup.py install"
script: nosetests

notifications:
  email:
    recipients:
      - alerts+ci@opengov.com
    on_success: change
    on_failure: always
